services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: cvbaza-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: .
      target: deps
    command: sh -c "npx drizzle-kit generate && npm run db:migrate"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}?schema=public
    depends_on:
      postgres:
        condition: service_healthy

  app:
    image: cvbaza
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}?schema=public
    build: .
    restart: always
    depends_on:
      migrations:
        condition: service_completed_successfully
    ports:
      - "${LOCAL_PORT}:${PORT}"
    container_name: cvbaza-app

volumes:
  db-data:
