import TestComponent from "@/components/test-component";
import { routing } from "@/i18n/routing";
import { auth } from "@/lib/auth";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Open_Sans } from "next/font/google";
import { notFound } from "next/navigation";
import "../globals.css";

const openSans = Open_Sans({
  subsets: ["latin", "cyrillic"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: React.ReactNode;
  params: Promise<{ locale: "en" | "ua" }>;
};

export default async function RootLayout({ children, params }: LayoutProps) {
  const { locale } = await params;
  const session = await auth();

  if (!routing.locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang="en">
      <body className={`${openSans.variable} font-sans antialiased`}>
        <SessionProvider session={session}>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <TestComponent />
            {children}
          </NextIntlClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
